--Question #2: 
--What is the revenue in 2022 and 2021 that has been 
--generated by the video ad types of both platforms combined? 
--Did the revenue grow?

SELECT years, 
       ROUND(SUM(revenue)::numeric,2)as total_revenue
FROM meta_revenue
WHERE ad_types LIKE '%Video%' and years in ('2021','2022')
GROUP BY years
ORDER BY years;









