--Question #3: 
--Create a column called “ad_products” that creates one value 
--that groups the Display ad types together 
--and one value that groups the Video ad types together. 

What is the total revenue generated by each ad product? 

WITH
  new_meta_rev AS (
    SELECT
      *,
      CASE
        WHEN ad_types LIKE '%Display%' THEN 'Display Ad'
        WHEN ad_types LIKE '%Video%' THEN 'Video Ad'
        ELSE 'Error'
      END AS ad_products
    FROM
      meta_revenue
  )
SELECT
  ad_products,
  ROUND(SUM(revenue)::numeric,2)
FROM
  new_meta_rev
GROUP BY
  ad_products;