--Question #3: 
--The real profit margin per order item is calculated by: (sales price - cost) / sales price. 
--By summing up all the order items, we will find the real profit margin generated by the products.
--Calculate the profit margin for the Nike Official products:
--Nike Pro Tights, Nike Dri-FIT Shorts, and Nike Legend Tee.
SELECT DISTINCT
  product_name,
  ROUND(((SUM(sale_price) - SUM(cost)) / SUM(sale_price))::numeric,2) as real_margin
FROM
  order_items o
  LEFT JOIN products p ON o.product_id = p.product_id
WHERE
  product_name IN (
    'Nike Pro Tights',
    'Nike Dri-FIT Shorts',
    'Nike Legend Tee'
  )
GROUP BY
  product_name
  ;